package rules

import com.zeltang.it.tools.drools.OrderRequestVo;
import com.zeltang.it.tools.drools.OrderTypeVo;

global com.zeltang.it.tools.drools.OrderDiscountVo orderDiscountVo;

dialect "mvel"

// 规则1: 根据年龄判断
rule "Age based discount"
when
// 当客户年龄在20岁以下或者50岁以上
OrderRequestVo(age < 20 || age > 50)
then
// 则添加10%的折扣
System.out.println("==========Adding 10% discount for Kids/ senior customer=============");
orderDiscountVo.setDiscount(orderDiscountVo.getDiscount() + 10);
end

// 规则2： 根据客户类型的规则
rule "Customer type based discount - Loyal customer"
when
// 当客户类型是LOYAL
OrderRequestVo(orderType.getValue == "LOYAL")
then
// 则增加5%的折扣
System.out.println("==========Adding 5% discount for LOYAL customer=============");
orderDiscountVo.setDiscount(orderDiscountVo.getDiscount() + 5);
end

rule "Customer type based discount - others"
when
OrderRequestVo(orderType.getValue != "LOYAL")
then
System.out.println("==========Adding 3% discount for NEW or DISSATISFIED customer=============");
orderDiscountVo.setDiscount(orderDiscountVo.getDiscount() + 3);
end